# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: gitpod/workspace-full:latest

tasks:
  - name: Init project and run server
    init: |
      # Create project directory
      mkdir /workspace/zelthy3/projects

      # Building zelthy3 base image
      python zel_setup.py --build_core

    command: |
      # Initializing project and starting server
      python zel_setup.py --project_dir=/workspace/zelthy3/projects/ --start
  
ports:
  - port: 8000
    onOpen: open-preview
    visibility: private
