# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: gitpod/workspace-full:latest

tasks:
  - name: Setup and start the project
    before: |
      # Create project directory
      mkdir /workspace/projects
    init: |
    
      docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
      
      # Pulling latest zelthy3 image
      docker pull $DOCKERHUB_USERNAME/zelthy3:latest

      docker tag $DOCKERHUB_USERNAME/zelthy3 zelthy3

    command: |
      # Initializing project and starting server
      python zel_setup.py --project_dir=/workspace/projects --platform_username=admin@zelthy.com --start
  
ports:
  - port: 8000
    onOpen: open-preview
    visibility: private


workspaceLocation: '/workspace/projects/'