name: Create build of Docusaurus app and push to Zelthy's Static Hosting Bucket
on:
  push:
    branches:
      - documentation

jobs:
  build-z-react-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./zelthy3/documentation/zelthy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn install

      - name: Building app
        run: CI=false yarn build

     - name: Deploy to S3 bucket
        run: aws s3 sync ./build s3://rajat-test-zelthy --delete # Adjust your S3 bucket name here
