name: ci-cd-workflow
on:
  push:
    branches:
      - documentation

jobs:
  my-job:
    uses: Healthlane-Technologies/zelthy-ci-cd-workflows/.github/workflows/deploy_docusaurus_build_to_s3.yml@v4
    with:
      static-bucket: zelthystatichosting
      AWS_REGION: ap-south-1
    secrets: inherit
